### ISSUE TITLE
Installing without Node

### ISSUE THREAD

**Issue by holgersindbaek** [centro/transis#33]
How would I install this library without Node? I'm trying to use it for my Rails/React app. Is there a single file all the files can be compiled down to that I can include?

**Comment by burrows** [comment]
We recommend using npm to install and then a module bundler like webpack or browserify. If thats not an option for you then you can build a single file package by cloning the repo and running the following commands:

```
$ npm install
$ make package
```

This will create a file called `dist/transis.js` that can be included into any webpage. It exposes a `Transis` object in the global scope. The example apps in the repo use this method.

**Comment by holgersindbaek** [comment]
Sounds like just what I need. I keep getting this error if I do that though:

    Uncaught TypeError: Cannot read property 'appendChild' of null(anonymous function) 
      Object.defineProperty.value 
      __webpack_require__ 
      Object.defineProperty.value
      __webpack_require__
      bject.defineProperty.value 
      (anonymous function) 
      webpackUniversalModuleDefinition 
      (anonymous function) 

Any guesses on what that might be about?

**Comment by holgersindbaek** [comment]
Seems like it has something to do with the following code:

    var TransisArray = (function () {
      // http://danielmendel.github.io/blog/2013/02/20/subclassing-javascript-arrays/

      if (typeof window !== "undefined") {
        // browser
        iframe = document.createElement("iframe");
        iframe.style.display = "none";
        document.body.appendChild(iframe);
        frames[frames.length - 1].document.write("<script>parent._Array = Array;</script>");
        var _Array = window._Array;
        delete window._Array;
        document.body.removeChild(iframe);
        return _Array;
      } else {
        // node.js
        return __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"vm\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())).runInNewContext("Array");
      }
    })();

If I include the transis.js file in the footer of my Rails app, then it works. How do I get it to work when I include it in the head of my app?

This is the error I'm seeing:

![screen shot 2016-05-30 at 3 27 11 pm](https://cloud.githubusercontent.com/assets/698979/15657009/0925f228-267b-11e6-889c-5179aa9b2abb.png)

**Comment by alexraginskiy** [comment]
Where are you including your script tag?  Try placing at the bottom of the body tag.

On May 30, 2016, at 2:27 PM, holgersindbaek <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems like it has something to do with the following code:

var TransisArray = (function () {
  // http://danielmendel.github.io/blog/2013/02/20/subclassing-javascript-arrays/

  if (typeof window !== "undefined") {
    // browser
    iframe = document.createElement("iframe");
    iframe.style.display = "none";
    document.body.appendChild(iframe);
    frames[frames.length - 1].document.write("<script>parent._Array = Array;</script>");
    var _Array = window._Array;
    delete window._Array;
    document.body.removeChild(iframe);
    return _Array;
  } else {
    // node.js
    return __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"vm\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())).runInNewContext("Array");
  }
})();


If I include the transis.js file in the footer of my Rails app, then it works. How do I get it to work when I include it in the head of my app?

This is the error I'm seeing:

[screen shot 2016-05-30 at 3 27 11 pm]<https://cloud.githubusercontent.com/assets/698979/15657009/0925f228-267b-11e6-889c-5179aa9b2abb.png>

**Comment by holgersindbaek** [comment]
That seems to work. Why is the document body needed when the file loads though? Is there a reason for that?

**Comment by alexraginskiy** [comment]
Transis clones an array by creating an iframe.  In order to create an iframe, it needs to append it to `document`. If your script is included in the head, it is executed before the rest of the document is loaded.

**Comment by holgersindbaek** [comment]
Ok. Is it possible to execute the functions after the body loads with something like this:

http://stackoverflow.com/questions/11936816/call-a-function-after-complete-page-load
