### ISSUE TITLE
Implement with Firebase

### ISSUE THREAD

**Issue by holgersindbaek** [centro/transis#34]
I'm sure this is a bit out of the scope of what Transis is supposed to do, but if you have a suggestion, I'd love to hear it - http://stackoverflow.com/questions/37535102/implementing-data-model-with-reactfire-or-re-base-firebase.

Creating a Transis model is easy, but I'm not sure how to listen for changes on Firebase and make all components that implement that model re-render. Do you have any experience with Firebase and Transis? Any suggestions?

**Comment by burrows** [comment]
I don't have any experience with Firebase, but Transis was designed to work with any persistence layer through its use of the data mapper pattern. You just need to assign your model class a mapper object that implements the following methods:

- query(params)
- get(id)
- create(model)
- update(model)
- delete(model)

As for listening for changes in firebase - what you'll probably want to do is make use of the [`Model.load`](https://github.com/centro/transis/blob/89fb5fd0a36fa9af7e31b6d369dd778c3c1fb03c/src/model.js#L392-L400) method in the listener callback. Munge the data you receive from firebase to match your model schema (if necessary) and then pass that to the `SomeModel.load`. This will load the data into the model layer, instantiating a new instance of `SomeModel` or updating the one already in the id map if its already been previously loaded. Observers are also notified, so if you are using the `ReactPropsMixin` then your views should automatically re-render.

**Comment by holgersindbaek** [comment]
Ok. Thanks for clearing that up. This is how my code ended up looking:

    @ListingView = React.createClass
      getInitialState: ->
        listing: new Listing(@props.listing)

      componentWillMount: ->
        # Listen for changes in listing
        @listingReference = firebase.database().ref("listings/#{@props.listing.id}")
        @listingReference.on 'value', (snap) =>
          @state.listing.update(snap.val())

        # Listen for changes on model
        @state.listing.on '*', =>
          @forceUpdate()

      componentWillUnmount: ->
        @listingReference.off()

      render: ->
        React.DOM.div
          className: "swipe_parent_container"

Just for reference.
