### ISSUE TITLE
Man-to-many relationship

### ISSUE THREAD

**Issue by paulschwoerer** [centro/transis#44]
Hi there,

is it possible to create a many-to-many relationship with Transis? If I'm defining my models this way (pseudo):

`Album { this.hasMany('arts', 'art', { inverse: 'albums' }); }`
`Art { this.hasMany('albums', 'album', { inverse: 'arts'}); }`

I'm getting the error "this[k].replace is not a function".

Hope you can help,
Paul

Edit: I found out, that this[k] is a native Array in this case, that's why method replace() is not found.

**Comment by burrows** [comment]
Yep, you can defined a many-to-many relationship like this:

```javascript
var Album = Transis.Model.extend('Album', function() {
  this.hasMany('arts', 'Art', { inverse: 'albums' });
});

var Art = Transis.Model.extend('Art', function() {
  this.hasMany('albums', 'Album', { inverse: 'arts' });
});

var album1 = Album.load({id: 1});
var album2 = Album.load({id: 2});
var art1 = Art.load({id: 1});
var art2 = Art.load({id: 2});

album1.arts.push(art1);
album1.arts.push(art2);

art1.albums.push(album2);

console.log(String(album1.arts)); // [#<Art (LOADED):3 {"id":1,"albums":[1,2]}>, #<Art (LOADED):4 {"id":2,"albums":[1]}>]
console.log(String(art1.albums)); // [#<Album (LOADED):1 {"id":1,"arts":[1,2]}>, #<Album (LOADED):2 {"id":2,"arts":[1]}>]
```

Make sure that the second argument to `hasMany` matches the name you pass to `Transis.Model.extend`. Thats necessary for Transis to resolve the associated class.

**Comment by paulschwoerer** [comment]
Seems to be a problem with my code then.
Thanks for the quick help and keep up the good work!
