### ISSUE TITLE
loadAll does not return a Transis Array

### ISSUE THREAD

**Issue by stallings** [centro/transis#49]
I just realised that `loadAll` does not return a Transis array. What do you think about adding that?

![image](https://user-images.githubusercontent.com/1040946/30498780-9202a264-9a1d-11e7-97ce-80a5220adfd3.png)

**Comment by burrows** [comment]
It just maps over the array of arguments you give it. So if you give it a regular array it will return a regular array, if you give it a Transis Array it will return a Transis Array.

I'm not sure that it needs to always return a Transis Array, what do you think?
